/**
 * SecDevOops API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { OrdenPago } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CampusControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param idStudent 
     */
    getCalifiaciones(idStudent: string, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param idStudent 
     */
    getListaActivitysFromRepresentante(idStudent: string, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param idRepre 
     */
    getOrders(idRepre: string, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param idRepre 
     */
    getPor100AssistByStudent(idRepre: string, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param idRepre 
     */
    getStudenByRepre(idRepre: string, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param idRepre 
     */
    getStudentByRepreToMatricula(idRepre: string, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param ordenPago 
     */
    putOrders(ordenPago: OrdenPago, extraHttpRequestParams?: any): Observable<object>;

}
