/**
 * SecDevOops API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PutDocumentMatriculaRequest } from '../model/models';
import { PutImgPerfilRequest } from '../model/models';
import { WebUser } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PublicControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    getAllCursos(extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param orde 
     */
    getCurstoTomatricula(orde: string, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param idCurso 
     */
    getMateriasByCurso(idCurso: string, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param document 
     */
    getStudentByDocument(document: string, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     */
    getTipAct(extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param user 
     * @param pass 
     */
    login(user: string, pass: string, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param iduser 
     * @param putImgPerfilRequest 
     */
    putDocumentIdentidad(iduser: string, putImgPerfilRequest?: PutImgPerfilRequest, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param iduser 
     * @param putDocumentMatriculaRequest 
     */
    putDocumentMatricula(iduser: string, putDocumentMatriculaRequest?: PutDocumentMatriculaRequest, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param iduser 
     * @param putImgPerfilRequest 
     */
    putImgPerfil(iduser: string, putImgPerfilRequest?: PutImgPerfilRequest, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param webUser 
     */
    putUser(webUser: WebUser, extraHttpRequestParams?: any): Observable<object>;

}
