/**
 * SecDevOops API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';



export interface StudentControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param idStudent 
     */
    getDetalleByAssist(idStudent: string, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param idStudent 
     */
    getListaAsistencia(idStudent: string, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param idDetalle 
     * @param file 
     */
    putActivityFile(idDetalle: string, file: Blob, extraHttpRequestParams?: any): Observable<object>;

}
