/**
 * SecDevOops API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdminUser { 
    id?: number;
    document?: string;
    name?: string;
    ape?: string;
    whatsapp?: string;
    usser: string;
    imgPerfi?: string;
    rol?: string;
    nameCurso?: string;
    activo?: boolean;
}

