/**
 * SecDevOops API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CatalogoEstados } from './catalogo-estados';
import { CatalogoCursos } from './catalogo-cursos';
import { WebUser } from './web-user';


export interface OrdenPago { 
    id?: number;
    codigo?: string;
    representante?: WebUser;
    estudiante?: WebUser;
    curso?: CatalogoCursos;
    fechaCreada?: string;
    fechaMaxPago?: string;
    total?: number;
    status?: CatalogoEstados;
    aceptaLicitudFondos?: boolean;
}

