/**
 * SecDevOops API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Materias } from './materias';
import { CatalogoTipoActividad } from './catalogo-tipo-actividad';
import { AdminUser } from './admin-user';


export interface RequestActivity { 
    nameTema?: string;
    materia?: Materias;
    docente?: AdminUser;
    fechaMaxEntrega?: string;
    tipo?: CatalogoTipoActividad;
    observacion?: string;
}

