/**
 * SecDevOops API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CatalogoCursos } from './catalogo-cursos';


export interface WebUser { 
    id?: number;
    document?: string;
    name?: string;
    ape?: string;
    whatsapp?: string;
    usser: string;
    pass?: string;
    imgPerfi?: string;
    imgDoc?: string;
    imgVac?: string;
    rol?: string;
    isMatriculate?: boolean;
    idRepre?: WebUser;
    lastCurso?: CatalogoCursos;
    currentCurso?: CatalogoCursos;
    activo?: boolean;
    conciliado?: boolean;
    aceptaInfoCorrecta?: boolean;
}

